name: Scan code with Snyk

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # To check out the code
      security-events: write  # To upload the SARIF results
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        # continue on develop PRs, fail on main PRs
        continue-on-error: ${{ github.base_ref == 'develop' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects

      - name: Upload result to GitHub Code Scanning
        # always try to upload even if Snyk failed
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
